### ISSUE TITLE
[Misc.] Compatibility with mod Inevitable Zero

### ISSUE THREAD

**Issue by Hopyoprop** [shinkiseki/MorePortraitsInZero#5]
Hi ShinKiseki, was just wondering about compatibility with the Inevitable Zero's mod by Kyuuhachi. As both mods modify the scena files I'm not too sure how compatible both mods will be with each other! Perhaps some clarification or a disclaimer on your README.md would be helpful if they aren't compatible. Or maybe 2 separate versions of the mod release could be possible for cross compatibility of both mods in the future once your mod is more finalised.

[Inevitable Zero Github](https://github.com/Kyuuhachi/Inevitable-Zero)

Also side note I didn't add the Misc label to this issue the normal way as I don't have the permissions to do so. Placed it in the title.

**Comment by Kyuuhachi** [comment]
I have updated my readme to mention this.

**Comment by shinkiseki** [comment]
Good idea, I'll add a section for mod compatibility.

As for the labels, thanks for letting me know -- it looks like only I'm able to add labels. I'll update the README to reflect this.

**Comment by flavio-a** [comment]
Sorry to bother, but I found out that installing this mod first and Inevitable Zero after, so that the latter's file replaces some of the former's, adds the new sidequests and also keeps some of the new potraits. Maybe it is worth mentioning somewhere?
As I'm currently (re)playing the game, I can only vouch for chapter 2 quests, but I was able to complete "_Ultimate Bread Showdown!_" and "_Search for the Oversleeping Doctor_". As for potraits, these are my results:
Characters with the potrait:
- Wendy
- Chaco
- Scott
- Wenzel
- Pierre
- Fernand
- Mireille
- Michel

Characters without the potrait:
- Lynn
- Aeolia
- Franz
- Bennet
- Oscar
- Abbas

Couldn't check:
- Sully

Everything was tested with the latest version of both mods (MorePotraits 1.0.1 and InevitableZero 2.1.0).

**Comment by Kyuuhachi** [comment]
I have made a compatibility patch, but I was waiting for Shin to add his faces to the Bread Showdown before publishing it. But I guess I should upload it in the interim. ([Link](https://github.com/Kyuuhachi/Inevitable-Zero/releases/tag/v2.1.1).)

Due to how the game is structured, scripts are separated by area, not by character. So if Inevitable Zero changes anything in, say, the Harbor District, this will overwrite that whole area and thus revert the faces Shin's added. In other words, it's not that Wendy keeps her portrait, it's that I don't touch the Genten interior's script.

**Comment by flavio-a** [comment]
Nice, thanks a lot!

**Comment by shinkiseki** [comment]
We've done some work behind the scenes to make a compatible version 😄 

First, install More Portraits in Zero. Then, install Inevitable Zero. (These instructions have also been added to the README)

There are some shared files between the two mods, so Inevitable Zero's files will overwrite those More Portraits files. However, since Kyuuhachi has added all the changes from More Portraits into Inevitable Zero, both the added portraits and added quests should be included. 

If you encounter any issues, please let me and Kyuuhachi know, and we can identify and address the problem!
